spring.application.name=InventorySystem

spring.datasource.url=jdbc:h2:mem:estoquedb

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=inventory.systemerp@gmail.com
spring.mail.password=${SENHA_EMAIL_APP}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true